[tools]
python = "latest"
yq = "latest"
jq = "latest"
ruff = "0.4.10" # lastest is breaking
go = "latest"
rust = "stable"
kubectl = "latest"
helm = "latest"
awscli = "latest"
kn = "latest"
pre-commit = "latest"
glow = "latest"
k9s = "latest"
direnv = "latest"
lazygit = "latest"
pulumi = "latest"
sqlite = "latest"
"npm:graphite" = "latest"

[env]
PLATFORM = "linux/amd64"
CORE_PULUMI_STACK = "pocketsizefund/development"
KUBEFLOW_PULUMI_STACK = "pocketsizefund/kubeflow"
