[project]
name = "tools"
version = "0.1.0"
description = "Project tools and scripts"
requires-python = "==3.12.10"
dependencies = [
  "loguru>=0.7.3",
  "sagemaker>=2.252.0",
  "boto3>=1.40.74",
  "loguru>=0.7.3",
]
