---
name: Create or update portfolio
on:
  schedule:
    - cron: 0 15 * * 1-5
jobs:
  create_or_update_portfolio:
    name: Create or update portfolio on weekday schedule
    runs-on: ubuntu-latest
    environment: pulumi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Create or update portfolio
        uses: flox/activate-action@v1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: mask infrastructure services invoke portfoliomanager
