---
name: Sync data
on:
  workflow_run:
    workflows:
      - Launch infrastructure
    types:
      - completed
jobs:
  fetch_data:
    name: Sync data on weekday schedule
    runs-on: ubuntu-latest
    environment: pulumi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Fetch with Pulumi
        uses: flox/activate-action@v1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: mask infrastructure services invoke datamanager
